name: ccb

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - gdal
  - geopandas
  - matplotlib
  - openjdk
  - pandas
  - psutil
  - python=3.7.6
  - scikit-learn
  - scipy
  - shapely
