name: ccb

channels:
  - conda-forge
  - defaults

dependencies:
  - argparse
  - black
  - flake8
  - flask
  - gdal
  - geopandas
  - glob
  - isort
  - matplotlib
  - pandas
  - pickle
  - pre-commit
  - psutil
  - pytest
  - pytest-cov
  - python-dotenv
  - python=3.7.6
  - scikit-learn
  - scipy
  - shapely