name: ccb-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7.6
  - black
  - flake8
  - gdal
  - geopandas
  - ipython
  - isort
  - matplotlib
  - openjdk
  - pandas
  - pre-commit
  - psutil
  - pytest
  - pytest-cov
  - python-dotenv
  - scikit-learn
  - scipy
  - shapely
